

#' Summarise raster files
#'
#' Rasters are stacked via [terra::rast()], then summaries are generated by
#' [terra::app()]. Summaries are saved to file. Rasters are split
#' by index (using [terra::subset()]) before summarising, allowing for
#' multi-layer rasters. Lyr`n` is added to filename.
#'
#' @param paths Character. Paths to any raster that can be read by
#' [terra::rast()].
#' @param process,season,epoch Character. Descriptors for rasters being
#' summarised. See [envEcosystems::env].
#' @param layer Numeric. Layer/band of `paths` to summarise. Only one band at a
#' time can be summarised.
#' @param out_dir Character. Path for saving summarised rasters.
#' @param force_new Logical. Run summarise even if resulting file already
#' exists.
#' @param methods Method(s) to apply to each vector of stacked cells. Name of
#' function(s).
#' @param out_type Extension for raster file written. Required as filename is
#' created from `out_base` and `method` so can't be passed directly.
#' @param ... Passed to [terra::app()]. Thus, (presumably) includes options to
#' [terra::writeRaster()] via `wopt` argument (untested).
#'
#' @return Side effect of saving summarised raster(s) to file.
#' @export
#'
#' @examples
#'
#'
summarise_rast_paths <- function(paths
                                 , process
                                 , season = NA
                                 , epoch = NA
                                 , layer = 1L
                                 , out_dir
                                 , force_new = FALSE
                                 , methods = c("mean", "median", "min", "max", "sd")
                                 , out_type = "tif"
                                 , ...
                                 ) {

  s <- terra::rast(as.character(paths))

  all_layers <- names(terra::rast(paths[[1]]))

  stacks <- tibble::tibble(layer_name = all_layers) %>%
    dplyr::mutate(layer_id = dplyr::row_number()
                  , subsets = purrr::map(layer_id
                                         , ~ seq(.
                                                 , length(all_layers)* length(paths)
                                                 , by = length(all_layers)
                                                 )
                                         )
                  ) %>%
    dplyr::filter(layer_id == layer) %>%
    dplyr::mutate(s = purrr::map(subsets
                                   , ~terra::subset(s
                                                    , .
                                                    )
                                   )
                  ) %>%
    dplyr::left_join(tibble::tibble(func = methods)
                     , by = character()
                     ) %>%
    dplyr::mutate(out_file = fs::path(out_dir
                                      , paste0(process
                                               , "_"
                                               , layer
                                               , "_"
                                               , func
                                               , "_"
                                               , season
                                               , "_"
                                               , epoch
                                               , "."
                                               , out_type
                                      )
    )
    )

  summarise_func <- function(lyr_stack
                             , func_name
                             , out_file
  ) {

    do <- !file.exists(out_file)

    if(force_new) do <- TRUE

    if(do) {

      terra::app(lyr_stack
                 , fun = get(func_name)
                 , filename = out_file
                 , ...
      )

    }

  }

  purrr::pwalk(list(stacks$s
                    , stacks$func
                    , stacks$out_file
  )
  , summarise_func
  )

}

